#!/usr/bin/env bash

export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export PATH=$PATH:~/.local/bin
export EDITOR=`which vim`
export GOPATH=$HOME/Go

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ext scripts
source ~/.bin/tmuxinator.bash
source ~/.bin/fabric-completion.bash
source ~/.bin/git-completion.bash

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Autocomple with sudo
complete -cf sudo

eval $(thefuck --alias)

NoColor="\[\e[0m\]"
Yellow="\[\e[1;33m\]"
LightGray="\[\e[0;37m\]"
Red="\[\e[00;31m\]"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

source ~/.git-prompt.sh
type -t __git_ps1 &>/dev/null
GIT=$?
PS1GIT=""
if [[ $GIT ]]; then
    PS1GIT=$Red'$(__git_ps1 "(%s)")'
fi
unset GIT

PS1="$PS1GIT $Yellow\$ $NoColor"

