#!/usr/bin/env bash

unset GREP_OPTIONS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

export PATH="$PATH:$(go env GOROOT)/bin:~/.composer/vendor/bin/:~/.local/bin:$HOME/.cargo/bin:$HOME/.yarn/bin"
export EDITOR=`which vim`
export GOPATH=$HOME/Go

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# ext scripts
. ~/.bin/tmuxinator.bash
. ~/.bin/fabric-completion.bash
. ~/.bin/git-completion.bash
. ~/.bin/composer-completion.bash
. ~/.bin/invoke-completion.bash
. ~/.bin/gh-completion.bash

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Autocomple with sudo
complete -cf sudo

eval $(thefuck --alias)

NoColor="\[\e[0m\]"
Yellow="\[\e[1;33m\]"
LightGray="\[\e[0;37m\]"
Red="\[\e[00;31m\]"

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true

type -t __git_ps1 &>/dev/null
GIT=$?
PS1GIT=""
if [[ $GIT ]]; then
    PS1GIT=$Red'$(__git_ps1 "(%s)")'
fi
unset GIT

PS1="$PS1GIT $Yellow\$ $NoColor"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/home/baptiste/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
source "$HOME/.cargo/env"
